version: '3'
services:
  app:
    container_name: ictshort_app
    build: ./go
    volumes:
      - ./go/app:/app:z
    ports:
      - 8080:80
    networks:
      - ictshort_network
  voicevox_engine:
    container_name: ictshort_voicevox_engine
    image: voicevox/voicevox_engine
    environment:
      - ALLOW_ORIGIN=ictshort_voicevox_engine
    restart: always
    ports:
      - 50021:50021
    networks:
      - ictshort_network
networks:
    ictshort_network:
        external: true
    
